### ISSUE TITLE
Change Semester of Study Groups in Upgrade and "alumni" Support

### ISSUE THREAD

**Issue by maxwai** [marcelropos/HM-DiscordBot#109]
We need to have some new rules during upgrade for the study groups:

## Upgrade scheme

- Semesters 1-6 are upgraded to 2-7 normally
- Semester 7 people are moved to a `7+` group, e.g. `IF7+`, `IB7+`, `DC7+`
- Students in Group `7+` are not moved

## Alumni

All students in Group 7+ can use the command `!alumni` to mark themself as an Alumni.

Changed for these students:

- These students can't add themself to courses
- They get, besides a `alumni` Role (that groups them), also a Role saying when/what they graduated (so when the command is made), e.g. `IF WS22/23`, `IF SS23`
- They keep their Study group chat as written bellow
- A special text channel for all Alumnis, not divided by study group

## Study group chats (`#IF4`, `#IB2`)

- Till 7 they count up normally as before
- As soon as the Group changes to 7+, the group chat is renamed to the group + start of the studies, e.g. `IF WS20/21` (for that a helper role can be made per group since all 7+ Students are in the same role)

# TODO:

- [x] change upgrade from 7 to 7+
- [x] implement upgrade for 7+: only remove subjects, nothing else
- [x] implement Alumni
- [x] change how groups chats are renamed after 7
- [x] don't rename group chats once named like `IF WS20/21`

## New Roles

- Alumni
- 7+ Roles
- helper roles for the text channel for 7+ (e.g. `IF WS20/21`) -> this may not need to be saved in the database since this is only used once during the upgrade to give the students and then never again
- Graduation roles

**Comment by maxwai** [comment]
This needs a redesign.

Here are a few things that need to be redone:

- study group chats renamed to the start of studies needs to be rethought
- alumni can be earlier then Semester 7
-
